dataset:
  path: ./data/rooms/dataset.npy

scene:
  xml_root: data

frequency:
  scale: 1000000000

edges:
  mode: full
  k_obj: 6
  k_tr: 8

node_features:
  z_pc:
    enabled: true
    dim: 64

  material:
    enabled: true
    dim: 8
    vocab_size: 64

  centroid: true
  bbox: true

  node_type:
    enabled: true
    dim: 3

  frequency:
    enabled: true
    dim: 1